-- YJ PO Generator -- Postgres schema for the shared-database backend (Batch 157+).
--
-- Hand-ported from po_core.py's own SQLite `SCHEMA` constant plus every
-- column since added by an `_ensure_column()` migration -- generated by
-- introspecting a real, freshly-migrated SQLite database (every table's
-- PRAGMA table_info(), cross-checked column by column against the SQLite
-- SCHEMA text for primary keys, foreign keys, UNIQUE constraints, and
-- indexes, none of which PRAGMA table_info() reports on its own).
--
-- This file is the backend's OWN schema, independent of po_core.py's
-- SCHEMA/`_ensure_schema_ddl()` -- the whole point of the new backend is
-- that it owns Postgres's schema lifecycle itself, so none of po_core.py's
-- SQLite-flavoured DDL (AUTOINCREMENT, PRAGMA, sqlite_master) ever needs
-- translating on the fly. Applied once, by hand, when the backend's
-- Postgres database is first set up (see server/README.md); safe to
-- re-run since every statement uses IF NOT EXISTS.
--
-- SQLite's own REAL storage is always an 8-byte IEEE double regardless of
-- how a column is declared, so every REAL column here is DOUBLE PRECISION
-- (Postgres's own REAL is single-precision and would lose money-figure
-- precision) -- everything else is a direct, literal column-for-column
-- match to what's actually in the SQLite schema today.
--
-- po_core.py's own query text uses SQLite's `COLLATE NOCASE` in 14 places
-- (case-insensitive username lookups at login, and several ORDER BY/WHERE
-- clauses for supplier, product, category and prefix names) -- untouched
-- by sql_translate.py's ?/:name/date-function rewriting since the SQL
-- text itself (`... COLLATE NOCASE`) is already valid, ordinary syntax
-- Postgres understands; the only thing actually missing is a collation
-- object by that name for it to resolve to. Postgres folds an unquoted
-- identifier to lowercase, so unquoted `COLLATE NOCASE` in a query
-- resolves to a collation literally named "nocase" -- defining one here,
-- once, makes every one of those 14 existing, unmodified query strings
-- work as-is. `deterministic = false` is what actually makes it
-- case-insensitive for equality comparisons (matching SQLite's own NOCASE
-- behavior), not just for sorting.
CREATE COLLATION IF NOT EXISTS nocase (provider = icu, locale = 'und-u-ks-level2', deterministic = false);

CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT
);

CREATE TABLE IF NOT EXISTS addresses (
    id SERIAL PRIMARY KEY,
    label TEXT NOT NULL,
    company TEXT DEFAULT '',
    address TEXT DEFAULT '',
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS suppliers (
    id SERIAL PRIMARY KEY,
    company_name TEXT NOT NULL,
    contact_name TEXT DEFAULT '',
    email TEXT DEFAULT '',
    cc_emails TEXT DEFAULT '',
    phone TEXT DEFAULT '',
    address TEXT DEFAULT '',
    active INTEGER DEFAULT 1,
    notes TEXT DEFAULT '',
    credit_limit DOUBLE PRECISION DEFAULT 0,
    credit_reset_at TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    supplier_id INTEGER NOT NULL DEFAULT 0,
    code TEXT DEFAULT '',
    name TEXT NOT NULL,
    last_price DOUBLE PRECISION DEFAULT 0,
    times_ordered INTEGER DEFAULT 0,
    updated_at TEXT,
    UNIQUE(supplier_id, name)
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    id SERIAL PRIMARY KEY,
    po_ref TEXT UNIQUE NOT NULL,
    status TEXT DEFAULT 'Draft',
    supplier_id INTEGER,
    supplier_company_name TEXT DEFAULT '',
    supplier_contact_name TEXT DEFAULT '',
    supplier_email TEXT DEFAULT '',
    supplier_cc_emails TEXT DEFAULT '',
    supplier_phone TEXT DEFAULT '',
    supplier_address TEXT DEFAULT '',
    delivery_label TEXT DEFAULT '',
    delivery_name TEXT DEFAULT '',
    delivery_address TEXT DEFAULT '',
    business_name TEXT DEFAULT '',
    company_number TEXT DEFAULT '',
    currency TEXT DEFAULT 'GBP',
    invoice_name TEXT DEFAULT '',
    invoice_address TEXT DEFAULT '',
    your_name TEXT DEFAULT '',
    bcc_emails TEXT DEFAULT '',
    total DOUBLE PRECISION DEFAULT 0,
    notes TEXT DEFAULT '',
    deleted INTEGER DEFAULT 0,
    created_at TEXT,
    updated_at TEXT,
    flagged_for_review INTEGER DEFAULT 0,
    zoho_exported INTEGER DEFAULT 0,
    zoho_exported_at TEXT DEFAULT '',
    purchase_owner TEXT DEFAULT '',
    fx_rate DOUBLE PRECISION DEFAULT 1.0,
    base_total DOUBLE PRECISION DEFAULT 0,
    zoho_po_status TEXT DEFAULT '',
    created_by_user_id INTEGER DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS po_items (
    id SERIAL PRIMARY KEY,
    po_id INTEGER NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    position INTEGER DEFAULT 0,
    qty INTEGER DEFAULT 1,
    code TEXT DEFAULT '',
    product TEXT DEFAULT '',
    price DOUBLE PRECISION DEFAULT 0,
    margin_vat INTEGER DEFAULT 0,
    original_qty DOUBLE PRECISION DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS po_events (
    id SERIAL PRIMARY KEY,
    po_id INTEGER NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    event TEXT NOT NULL,
    detail TEXT DEFAULT '',
    at TEXT
);

CREATE INDEX IF NOT EXISTS idx_po_ref ON purchase_orders(po_ref);
CREATE INDEX IF NOT EXISTS idx_po_status ON purchase_orders(status);
CREATE INDEX IF NOT EXISTS idx_po_deleted ON purchase_orders(deleted);
CREATE INDEX IF NOT EXISTS idx_po_supplier ON purchase_orders(supplier_company_name);
CREATE INDEX IF NOT EXISTS idx_items_po ON po_items(po_id);
CREATE INDEX IF NOT EXISTS idx_events_po ON po_events(po_id);
CREATE INDEX IF NOT EXISTS idx_products_name ON products(name);
CREATE INDEX IF NOT EXISTS idx_products_supplier ON products(supplier_id);

CREATE TABLE IF NOT EXISTS product_merge_ignored (
    product_id_a INTEGER,
    product_id_b INTEGER,
    PRIMARY KEY(product_id_a, product_id_b)
);

CREATE TABLE IF NOT EXISTS supplier_merge_ignored (
    supplier_id_a INTEGER,
    supplier_id_b INTEGER,
    PRIMARY KEY(supplier_id_a, supplier_id_b)
);

-- Batch 157: seq replaces reliance on SQLite's implicit rowid -- see
-- po_core.py's _ensure_schema_ddl()/set_zoho_vendor_map() comments.
CREATE TABLE IF NOT EXISTS zoho_vendor_map (
    zoho_vendor_name TEXT PRIMARY KEY,
    supplier_id INTEGER NOT NULL,
    seq INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS supplier_issues (
    id SERIAL PRIMARY KEY,
    supplier_company_name TEXT NOT NULL,
    note TEXT NOT NULL,
    at TEXT,
    category TEXT DEFAULT '',
    subject TEXT DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_supplier_issues_name ON supplier_issues(supplier_company_name);

CREATE TABLE IF NOT EXISTS price_requests (
    id SERIAL PRIMARY KEY,
    product_name TEXT NOT NULL,
    qty INTEGER DEFAULT 1,
    notes TEXT DEFAULT '',
    created_at TEXT
);

CREATE TABLE IF NOT EXISTS price_request_replies (
    id SERIAL PRIMARY KEY,
    request_id INTEGER NOT NULL REFERENCES price_requests(id) ON DELETE CASCADE,
    supplier_id INTEGER,
    supplier_company_name TEXT DEFAULT '',
    status TEXT DEFAULT 'pending',
    price DOUBLE PRECISION,
    notes TEXT DEFAULT '',
    sent_at TEXT,
    replied_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_price_reply_request ON price_request_replies(request_id);
CREATE INDEX IF NOT EXISTS idx_price_requests_product ON price_requests(product_name);

CREATE TABLE IF NOT EXISTS savings_categories (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    sort_order INTEGER DEFAULT 0,
    active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS savings (
    id SERIAL PRIMARY KEY,
    category TEXT NOT NULL DEFAULT '',
    po_ref TEXT DEFAULT '',
    product TEXT DEFAULT '',
    supplier_company_name TEXT DEFAULT '',
    qty DOUBLE PRECISION DEFAULT 0,
    previous_price DOUBLE PRECISION,
    new_price DOUBLE PRECISION,
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    note TEXT DEFAULT '',
    created_at TEXT,
    deleted INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_savings_created ON savings(created_at);
CREATE INDEX IF NOT EXISTS idx_savings_product ON savings(product);
CREATE INDEX IF NOT EXISTS idx_savings_po_ref ON savings(po_ref);
CREATE INDEX IF NOT EXISTS idx_savings_supplier ON savings(supplier_company_name);

CREATE TABLE IF NOT EXISTS supplier_issue_categories (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    sort_order INTEGER DEFAULT 0,
    active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS purchase_owner_prefixes (
    id SERIAL PRIMARY KEY,
    prefix TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS po_receiving_events (
    id SERIAL PRIMARY KEY,
    source_event_id TEXT NOT NULL UNIQUE,
    po_id INTEGER NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    po_item_id INTEGER NOT NULL REFERENCES po_items(id) ON DELETE CASCADE,
    status TEXT NOT NULL,
    qty DOUBLE PRECISION,
    note TEXT DEFAULT '',
    device_id TEXT DEFAULT '',
    reported_at TEXT,
    applied_at TEXT
);
CREATE INDEX IF NOT EXISTS idx_receiving_events_item ON po_receiving_events(po_item_id);
CREATE INDEX IF NOT EXISTS idx_receiving_events_po ON po_receiving_events(po_id);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    full_name TEXT NOT NULL DEFAULT '',
    password_hash TEXT NOT NULL,
    password_salt TEXT NOT NULL,
    is_admin INTEGER DEFAULT 0,
    active INTEGER DEFAULT 1,
    must_set_password INTEGER NOT NULL DEFAULT 0,
    created_at TEXT,
    updated_at TEXT,
    dashboard_widgets TEXT DEFAULT NULL,
    notification_role TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS user_permissions (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    permission_key TEXT NOT NULL,
    PRIMARY KEY (user_id, permission_key)
);

CREATE TABLE IF NOT EXISTS notifications (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type_key TEXT NOT NULL,
    title TEXT NOT NULL,
    body TEXT DEFAULT '',
    link_page TEXT DEFAULT '',
    link_id TEXT DEFAULT '',
    created_at TEXT,
    read_at TEXT DEFAULT '',
    windows_shown INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications(user_id, read_at);

CREATE TABLE IF NOT EXISTS product_requests (
    id SERIAL PRIMARY KEY,
    kind TEXT NOT NULL DEFAULT 'existing',
    product_id INTEGER DEFAULT 0,
    product_name TEXT NOT NULL,
    supplier_id INTEGER DEFAULT 0,
    qty INTEGER DEFAULT 0,
    notes TEXT DEFAULT '',
    requested_by INTEGER NOT NULL REFERENCES users(id),
    status TEXT NOT NULL DEFAULT 'open',
    created_at TEXT,
    ordered_at TEXT DEFAULT '',
    po_id INTEGER DEFAULT 0,
    resolved_at TEXT DEFAULT '',
    resolved_by INTEGER DEFAULT 0,
    resolved_note TEXT DEFAULT ''
);
CREATE INDEX IF NOT EXISTS idx_product_requests_status ON product_requests(status);
